// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/record.proto

package rpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record_RecordStatus int32

const (
	Record_inprogress Record_RecordStatus = 0
	Record_completed  Record_RecordStatus = 1
	Record_absent     Record_RecordStatus = 2
	Record_failed     Record_RecordStatus = 3
)

var Record_RecordStatus_name = map[int32]string{
	0: "inprogress",
	1: "completed",
	2: "absent",
	3: "failed",
}

var Record_RecordStatus_value = map[string]int32{
	"inprogress": 0,
	"completed":  1,
	"absent":     2,
	"failed":     3,
}

func (x Record_RecordStatus) String() string {
	return proto.EnumName(Record_RecordStatus_name, int32(x))
}

func (Record_RecordStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aad9a9e93120e704, []int{3, 0}
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Record               *Record  `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_aad9a9e93120e704, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_aad9a9e93120e704, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RecordID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordID) Reset()         { *m = RecordID{} }
func (m *RecordID) String() string { return proto.CompactTextString(m) }
func (*RecordID) ProtoMessage()    {}
func (*RecordID) Descriptor() ([]byte, []int) {
	return fileDescriptor_aad9a9e93120e704, []int{2}
}

func (m *RecordID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordID.Unmarshal(m, b)
}
func (m *RecordID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordID.Marshal(b, m, deterministic)
}
func (m *RecordID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordID.Merge(m, src)
}
func (m *RecordID) XXX_Size() int {
	return xxx_messageInfo_RecordID.Size(m)
}
func (m *RecordID) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordID.DiscardUnknown(m)
}

var xxx_messageInfo_RecordID proto.InternalMessageInfo

func (m *RecordID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Record struct {
	Id                   string              `protobuf:"bytes,1,opt,name=RecordingSid,proto3" json:"RecordingSid,omitempty"`
	Duration             string              `protobuf:"bytes,2,opt,name=RecordingDuration,proto3" json:"RecordingDuration,omitempty"`
	Status               Record_RecordStatus `protobuf:"varint,3,opt,name=RecordingStatus,proto3,enum=rpc.Record_RecordStatus" json:"RecordingStatus,omitempty"`
	Url                  string              `protobuf:"bytes,4,opt,name=RecordingUrl,proto3" json:"RecordingUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_aad9a9e93120e704, []int{3}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Record) GetStatus() Record_RecordStatus {
	if m != nil {
		return m.Status
	}
	return Record_inprogress
}

func (m *Record) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterEnum("rpc.Record_RecordStatus", Record_RecordStatus_name, Record_RecordStatus_value)
	proto.RegisterType((*Response)(nil), "rpc.Response")
	proto.RegisterType((*Error)(nil), "rpc.Error")
	proto.RegisterType((*RecordID)(nil), "rpc.RecordID")
	proto.RegisterType((*Record)(nil), "rpc.Record")
}

func init() { proto.RegisterFile("rpc/record.proto", fileDescriptor_aad9a9e93120e704) }

var fileDescriptor_aad9a9e93120e704 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x41, 0x6e, 0xd4, 0x30,
	0x14, 0x86, 0x49, 0x86, 0x0e, 0x33, 0xaf, 0x9d, 0x51, 0x70, 0x37, 0x21, 0x42, 0x55, 0x08, 0x9b,
	0x6a, 0xc4, 0x24, 0x65, 0xd8, 0xcd, 0x8a, 0x56, 0x53, 0xa1, 0x22, 0x75, 0x13, 0x2e, 0x80, 0xc7,
	0x79, 0xb8, 0x66, 0x92, 0xd8, 0xd8, 0x0e, 0x2c, 0x10, 0x1b, 0x8e, 0x00, 0x4b, 0x16, 0x88, 0x93,
	0x70, 0x08, 0xae, 0xc0, 0x41, 0x50, 0x9c, 0x0c, 0x8a, 0xda, 0x95, 0xfd, 0xde, 0xff, 0xf9, 0xf7,
	0xef, 0xbc, 0x40, 0xa0, 0x15, 0xcb, 0x34, 0x32, 0xa9, 0x8b, 0x54, 0x69, 0x69, 0x25, 0x19, 0x69,
	0xc5, 0xa2, 0xc7, 0x5c, 0x4a, 0x5e, 0x62, 0x46, 0x95, 0xc8, 0x68, 0x5d, 0x4b, 0x4b, 0xad, 0x90,
	0xb5, 0xe9, 0x90, 0xe8, 0x99, 0x5b, 0xd8, 0x92, 0x63, 0xbd, 0x34, 0x9f, 0x28, 0xe7, 0xa8, 0x33,
	0xa9, 0x1c, 0x71, 0x97, 0x4e, 0x28, 0x4c, 0x72, 0x34, 0x4a, 0xd6, 0x06, 0xc9, 0x1c, 0x7c, 0xb9,
	0x0b, 0xbd, 0xd8, 0x3b, 0x9d, 0xe4, 0xbe, 0xdc, 0x91, 0xa7, 0x30, 0xee, 0x2e, 0x0f, 0xfd, 0xd8,
	0x3b, 0x3d, 0x5c, 0x1d, 0xa6, 0x5a, 0xb1, 0x34, 0x77, 0xad, 0xbc, 0x97, 0x48, 0x0c, 0x07, 0xa8,
	0xb5, 0xd4, 0xe1, 0xc8, 0x31, 0xe0, 0x98, 0xcb, 0xb6, 0x93, 0x77, 0x42, 0xf2, 0x04, 0x0e, 0x5c,
	0x4d, 0x42, 0x78, 0x50, 0xa1, 0x31, 0x94, 0xa3, 0xbb, 0x64, 0x9a, 0xef, 0xcb, 0x24, 0x6a, 0x53,
	0xb4, 0x76, 0x57, 0x9b, 0x36, 0x85, 0x28, 0x7a, 0xc0, 0x17, 0x45, 0xf2, 0xdb, 0x83, 0x71, 0x27,
	0xde, 0x96, 0x48, 0x04, 0x93, 0xa2, 0xd1, 0xee, 0x3d, 0x2e, 0xe2, 0x34, 0xff, 0x5f, 0x93, 0x33,
	0x18, 0x1b, 0x4b, 0x6d, 0x63, 0x5c, 0xb0, 0xf9, 0x2a, 0x1c, 0x84, 0xef, 0x97, 0x37, 0x4e, 0xcf,
	0x7b, 0x8e, 0x04, 0x30, 0x6a, 0x74, 0x19, 0xde, 0x77, 0x46, 0xed, 0x36, 0xb9, 0x84, 0xa3, 0x21,
	0x49, 0xe6, 0x00, 0xa2, 0x56, 0x5a, 0x72, 0x8d, 0xc6, 0x04, 0xf7, 0xc8, 0x0c, 0xa6, 0x4c, 0x56,
	0xaa, 0x44, 0x8b, 0x45, 0xe0, 0x11, 0x80, 0x31, 0xdd, 0x1a, 0xac, 0x6d, 0xe0, 0xb7, 0xfb, 0x77,
	0x54, 0x94, 0x58, 0x04, 0xa3, 0xd5, 0x2f, 0x0f, 0x66, 0xbd, 0x0f, 0xea, 0x8f, 0x82, 0x21, 0xd9,
	0xc0, 0xf4, 0x15, 0xda, 0xfe, 0x55, 0xb3, 0x41, 0xb2, 0xab, 0x4d, 0xb4, 0x2f, 0xbb, 0xa1, 0x24,
	0x8f, 0xbe, 0xfe, 0xf9, 0xfb, 0xdd, 0x3f, 0x26, 0x0f, 0xdd, 0xb8, 0xbb, 0x8f, 0x6e, 0xb2, 0xcf,
	0xa2, 0xf8, 0x42, 0x5e, 0xc3, 0xd1, 0x05, 0x65, 0xbb, 0x46, 0xf5, 0x46, 0xc3, 0xf9, 0xdc, 0xb6,
	0x39, 0x71, 0x36, 0x61, 0x72, 0x3c, 0xb4, 0x49, 0xb7, 0xee, 0xf8, 0xda, 0x5b, 0x5c, 0xfc, 0xf4,
	0xbe, 0x9d, 0xff, 0xf0, 0xc8, 0x07, 0x98, 0x70, 0xad, 0xd8, 0x52, 0x49, 0x96, 0xbc, 0x85, 0x93,
	0x0d, 0xad, 0x05, 0x96, 0xf1, 0x79, 0xc3, 0x1b, 0x63, 0x65, 0xbc, 0xc1, 0xf8, 0x1a, 0x4b, 0x19,
	0x5f, 0x4b, 0x8d, 0x42, 0x53, 0xb2, 0xb8, 0xb1, 0x56, 0x99, 0x75, 0x96, 0x71, 0x61, 0x6f, 0x9a,
	0x6d, 0xca, 0x64, 0x95, 0x75, 0x47, 0x96, 0x3d, 0x92, 0xed, 0xdd, 0x22, 0x52, 0xd0, 0xaa, 0xda,
	0xd1, 0x4a, 0xbc, 0xe4, 0x15, 0x15, 0x65, 0xcb, 0xae, 0x46, 0xcf, 0xd3, 0xb3, 0x85, 0xef, 0xf9,
	0xab, 0x80, 0x2a, 0x55, 0x0a, 0xe6, 0x26, 0x97, 0xbd, 0x37, 0xb2, 0x5e, 0xdf, 0xe9, 0x6c, 0xc7,
	0xee, 0x87, 0x7d, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x80, 0xf1, 0xaa, 0x38, 0x15, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordServiceClient is the client API for RecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordServiceClient interface {
	GetRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Response, error)
	BackupRecord(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Response, error)
}

type recordServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecordServiceClient(cc *grpc.ClientConn) RecordServiceClient {
	return &recordServiceClient{cc}
}

func (c *recordServiceClient) GetRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.RecordService/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) BackupRecord(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.RecordService/BackupRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServiceServer is the server API for RecordService service.
type RecordServiceServer interface {
	GetRecord(context.Context, *RecordID) (*Response, error)
	BackupRecord(context.Context, *Record) (*Response, error)
}

// UnimplementedRecordServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecordServiceServer struct {
}

func (*UnimplementedRecordServiceServer) GetRecord(ctx context.Context, req *RecordID) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (*UnimplementedRecordServiceServer) BackupRecord(ctx context.Context, req *Record) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupRecord not implemented")
}

func RegisterRecordServiceServer(s *grpc.Server, srv RecordServiceServer) {
	s.RegisterService(&_RecordService_serviceDesc, srv)
}

func _RecordService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.RecordService/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).GetRecord(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_BackupRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).BackupRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.RecordService/BackupRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).BackupRecord(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.RecordService",
	HandlerType: (*RecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecord",
			Handler:    _RecordService_GetRecord_Handler,
		},
		{
			MethodName: "BackupRecord",
			Handler:    _RecordService_BackupRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/record.proto",
}
